apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudsql-proxy-production
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudsql-proxy-production
  template:
    metadata:
      labels:
        app: cloudsql-proxy-production
    spec:
      containers:
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.31.2
        command: ["/cloud_sql_proxy",
                  "-instances=sodium-port-454223-m6:us-central1:socialapp-db=tcp:0.0.0.0:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials

